### ISSUE TITLE
Option fields in case classes are null in the constructor when unpickling

### ISSUE THREAD

**Issue by bardurdam** [scala/pickling#128]
```scala
import org.scalatest.FunSuite
import scala.pickling._, Defaults._
import json._

class Test extends FunSuite {
  test("main") {
    val a = A(Some(5))
    val pickle = a.pickle
    assert(pickle.unpickle[A] === a)
  }
}
case class A(intOpt: Option[Int]) {
  intOpt match {
    case Some(int) ⇒ 
    case None ⇒
  }
}
```
results in
```
[info] Test:
[info] - main *** FAILED ***
[info]   scala.MatchError: null
[info]   at A.<init>(Test.scala:14)
```

**Comment by eed3si9n** [comment]
I was able to reproduce this using Pickling 0.10.0.

```
[info] Test:
[info] - main *** FAILED ***
[info]   scala.MatchError: null
[info]   at A.<init>(test.scala:13)
[info]   at Test$$anonfun$1$AUnpickler$macro$5$2$.unpickle(test.scala:9)
[info]   at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[info]   at Test$$anonfun$1$AUnpickler$macro$5$2$.unpickleEntry(test.scala:9)
[info]   at scala.pickling.functions$.unpickle(functions.scala:11)
[info]   at scala.pickling.UnpickleOps.unpickle(Ops.scala:23)
[info]   at Test$$anonfun$1.apply$mcV$sp(test.scala:9)
[info]   at Test$$anonfun$1.apply(test.scala:6)
[info]   at Test$$anonfun$1.apply(test.scala:6)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
```

**Comment by jsuereth** [comment]
This appears to be fixed with the new pickling macros, or by @phaller's changes.
