### ISSUE TITLE
Pickling an ArrayBuffer fails on Android: ExceptionInInitializerError

### ISSUE THREAD

**Issue by RyanGlScott** [scala/pickling#140]
I'm not sure if `pickling` has ever been used on Android before, so I decided to take the plunge and try it out with [`android-sdk-plugin`](https://github.com/pfn/android-sdk-plugin). Unsurprisingly, things broke. Here's the class I'm using:

``` scala
package com.rscott.utils.scaloid

import android.app.Activity
import android.os.Bundle
import android.widget.Toast

import scala.collection.mutable
import scala.pickling._
import scala.pickling.binary._

class MainActivity extends Activity {

  override def onCreate(inState: Bundle): Unit = {
    super.onCreate(inState)

    if (inState != null) {
      val byteArray = inState.getByteArray("buf")
      val arrayBuffer = byteArray.unpickle[mutable.ArrayBuffer[Int]]
      Toast.makeText(this, arrayBuffer.toString(), Toast.LENGTH_SHORT).show()
    }
  }

  override def onSaveInstanceState(outState: Bundle): Unit = {
    super.onSaveInstanceState(outState)

    val arrayBuffer = mutable.ArrayBuffer(1, 2, 3, 4, 5)
    val pickle = arrayBuffer.pickle
    val byteArray = pickle.value
    outState.putByteArray("buf", byteArray)
  }
}
```

Upon rotating the device (which calls `onSaveInstanceState()`, the app crashes with this Logcat stack trace:

```
06-25 23:31:52.469  27064-27064/com.rscott.utils.scaloid W/dalvikvm﹕ dvmFindClassByName rejecting '<root>.package'
06-25 23:31:52.479  27064-27064/com.rscott.utils.scaloid W/dalvikvm﹕ dvmFindClassByName rejecting '<root>.scala'
06-25 23:31:52.549  27064-27064/com.rscott.utils.scaloid W/dalvikvm﹕ Exception Ljava/lang/NoSuchMethodException; thrown while initializing Lscala/pickling/FastTypeTag$;
06-25 23:31:52.549  27064-27064/com.rscott.utils.scaloid W/dalvikvm﹕ Exception Ljava/lang/ExceptionInInitializerError; thrown while initializing Lscala/pickling/binary/package$;
06-25 23:31:52.549  27064-27064/com.rscott.utils.scaloid D/AndroidRuntime﹕ Shutting down VM
06-25 23:31:52.549  27064-27064/com.rscott.utils.scaloid W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x415647c0)
06-25 23:31:52.559  27064-27064/com.rscott.utils.scaloid E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
            at scala.pickling.binary.BinaryPickleFormat.<init>(BinaryPickleFormat.scala:268)
            at scala.pickling.binary.package$.<init>(BinaryPickleFormat.scala:8)
            at scala.pickling.binary.package$.<clinit>(BinaryPickleFormat.scala)
            at com.rscott.utils.scaloid.MainActivity.onSaveInstanceState(MainActivity.scala:27)
            at android.app.Activity.performSaveInstanceState(Activity.java:1147)
            at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1223)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3842)
            at android.app.ActivityThread.access$700(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1275)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoSuchMethodException: bytes []
            at java.lang.Class.getConstructorOrMethod(Class.java:423)
            at java.lang.Class.getMethod(Class.java:787)
            at scala.reflect.runtime.JavaMirrors$JavaMirror.loadBytes$1(JavaMirrors.scala:553)
            at scala.reflect.runtime.JavaMirrors$JavaMirror.unpickleClass(JavaMirrors.scala:560)
            at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.complete(SymbolLoaders.scala:32)
            at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
            at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:244)
            at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:300)
            at scala.reflect.runtime.SymbolLoaders$LazyPackageType.complete(SymbolLoaders.scala:89)
            at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
            at scala.reflect.internal.Definitions$DefinitionsClass.AnyValClass$lzycompute(Definitions.scala:275)
            at scala.reflect.internal.Definitions$DefinitionsClass.AnyValClass(Definitions.scala:275)
            at scala.reflect.runtime.JavaMirrors$class.init(JavaMirrors.scala:50)
            at scala.reflect.runtime.JavaUniverse.init(JavaUniverse.scala:12)
            at scala.reflect.runtime.JavaUniverse.<init>(JavaUniverse.scala:26)
            at scala.reflect.runtime.package$.universe$lzycompute(package.scala:16)
            at scala.reflect.runtime.package$.universe(package.scala:16)
            at scala.pickling.FastTypeTag$.<init>(FastTags.scala:23)
            at scala.pickling.FastTypeTag$.<clinit>(FastTags.scala)
            at scala.pickling.binary.BinaryPickleFormat.<init>(BinaryPickleFormat.scala:268)
            at scala.pickling.binary.package$.<init>(BinaryPickleFormat.scala:8)
            at scala.pickling.binary.package$.<clinit>(BinaryPickleFormat.scala)
            at com.rscott.utils.scaloid.MainActivity.onSaveInstanceState(MainActivity.scala:27)
            at android.app.Activity.performSaveInstanceState(Activity.java:1147)
            at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1223)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3842)
            at android.app.ActivityThread.access$700(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1275)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)
```

So for some reason, `val pickle = arrayBuffer.pickle` is triggering the crash. I am using `pickling-0.8.0` with Scala 2.10.4 (I've also tried 2.11.1, but I experienced the same error).

**Comment by RyanGlScott** [comment]
Closing stale issue.
