### ISSUE TITLE
Pickling for nested structures (graphs)

### ISSUE THREAD

**Issue by timtinny** [scala/pickling#171]
I have the following graph structure:

``` scala
abstract class Node
case class NonLeaf(refs: Seq[Node]) extends Node
case class Leaf(value: Int) extends Node
```

When I try to pickle, I get the following error:

```
scala
scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
  at scala.pickling.PicklerUnpicklerNotFound.pickle(Custom.scala:22)
 ...
```

[This test case](https://github.com/scala/pickling/blob/0.9.x/core/src/test/scala/pickling/run/nested-non-primitive-subclass.scala)  shows how a simple nested structure can work. But, I could not make it for a generic graph.

Is there a way to write custom pickler for this generic case?

**Comment by eed3si9n** [comment]
Using Pickling 0.10.0, I was able to pickle the graph, but I was not able to unpickle back to `Node`.

``` scala
import scala.pickling._, Defaults._, json._

object PicklerTest extends App {
  @directSubclasses(Array(classOf[NonLeaf], classOf[Leaf]))
  sealed abstract class Node
  case class NonLeaf(refs: Seq[Node]) extends Node
  case class Leaf(value: Int) extends Node

  val one = Leaf(1)
  val two = Leaf(2)

  val root = NonLeaf(Seq(one, two))

  val pickledValue  = root.pickle
  println(pickledValue)
  val obj = pickledValue.unpickle[Node]
  println(obj)
}
```

Here's the output I got:

```
scala-pickling> sandbox/run
[info] Running PicklerTest 
JSONPickle({
  "$type": "PicklerTest.NonLeaf",
  "refs": {
    "$type": "scala.collection.Seq[PicklerTest.Node]",
    "elems": [
      {
      "$type": "PicklerTest.Leaf",
      "value": 1
    },
      {
      "$type": "PicklerTest.Leaf",
      "value": 2
    }
    ]
  }
})
[error] (run-main-5) scala.pickling.PicklingException: Tag PicklerTest.Node not recognized, looking for one of: PicklerTest.NonLeaf, PicklerTest.Leaf
scala.pickling.PicklingException: Tag PicklerTest.Node not recognized, looking for one of: PicklerTest.NonLeaf, PicklerTest.Leaf
    at PicklerTest$PicklerTestNodeUnpickler$macro$17$2$.unpickle(test.scala:16)
    at scala.pickling.pickler.TravPickler$$anon$1.unpickle(Iterable.scala:65)
    at PicklerTest$PicklerTestNodeUnpickler$macro$17$2$PicklerTestNonLeafUnpickler$macro$18$2$.unpickle(test.scala:16)
    at PicklerTest$PicklerTestNodeUnpickler$macro$17$2$.unpickle(test.scala:16)
    at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
    at PicklerTest$PicklerTestNodeUnpickler$macro$17$2$.unpickleEntry(test.scala:16)
    at scala.pickling.functions$.unpickle(functions.scala:11)
    at scala.pickling.UnpickleOps.unpickle(Ops.scala:23)
    at PicklerTest$.delayedEndpoint$PicklerTest$1(test.scala:16)
    at PicklerTest$delayedInit$body.apply(test.scala:3)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at PicklerTest$.main(test.scala:3)
    at PicklerTest.main(test.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
```
