### ISSUE TITLE
pickling fails with null pointer exception when pickling multi-dimensional arrays to json

### ISSUE THREAD

**Issue by jportway** [scala/pickling#179]
the following code fails with a null pointer exception when pickling to a json output, but seems to work ok with a binary output

```scala
import scala.pickling._
import json._

val original: Array[Array[Double]] =Array.fill(3,3){123.456}
val pickled=original.pickle
```

here's the exception I'm getting :

```
java.lang.NullPointerException
	at stain.ants.PicklingTest$$anonfun$2$$anonfun$apply$5$ScalaArray$u005BscalaDouble$u005DPickler$macro$1$2$.pickle(PicklingTest.scala:21)
	at stain.ants.PicklingTest$$anonfun$2$$anonfun$apply$5$ScalaArray$u005BscalaDouble$u005DPickler$macro$1$2$.pickle(PicklingTest.scala:21)
	at stain.ants.PicklingTest$$anonfun$2$$anonfun$apply$5.apply(PicklingTest.scala:21)
	at stain.ants.PicklingTest$$anonfun$2$$anonfun$apply$5.apply(PicklingTest.scala:19)
```

**Comment by eed3si9n** [comment]
This works using Pickling 0.10.0.

``` scala
scala> import scala.pickling._, Defaults._, json._
import scala.pickling._
import Defaults._
import json._

scala> val original: Array[Array[Double]] =Array.fill(3,3){123.456}
original: Array[Array[Double]] = Array(Array(123.456, 123.456, 123.456), Array(123.456, 123.456, 123.456), Array(123.456, 123.456, 123.456))

scala> val pickled=original.pickle
pickled: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "scala.Array[scala.Array[scala.Double]]",
  "elems": [
  [
    123.456,
    123.456,
    123.456
  ],
  [
    123.456,
    123.456,
    123.456
  ],
  [
    123.456,
    123.456,
    123.456
  ]
  ]
})
```
