### ISSUE TITLE
Constant val is omitted from pickle causing NPE on unpickle

### ISSUE THREAD

**Issue by dallmeier** [scala/pickling#180]
I have an abstract class that extends a trait with an abstract `val`, and a case class that extends the abstract class:

``` scala
package pickling.run

import org.scalatest.FunSuite
import scala.pickling._
import json._

trait TheTrait {
  val name : String
}

sealed abstract class BaseClass extends TheTrait {
  val name = "TestName"
}

case class TheClass(value : Int) extends BaseClass

/**
 */
class TraitWithAbstractValueTest extends FunSuite {

  test("main") {
    val instance = TheClass(1)
    val pickle = instance.pickle
    println(pickle.value)
  }

}
```

I would expect the generated pickle to contain val `name`. However, the output I get is:

``` json
{
  "tpe": "pickling.run.TheClass",
  "value": 1
}
```

**Comment by eed3si9n** [comment]
I am still seeing NPE for https://github.com/scala/pickling/issues/180#issuecomment-54806095 with Pickling 0.10.0.

```
{
  "$type": "pickling.run.EventMessage",
  "id": "theid",
  "ev": {
    "$type": "pickling.run.StartSpecializedTaskEvent",
    "value": 1
  }
}

[info] TraitWithAbstractValueTest:
[info] - main *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at pickling.run.EventMessage.<init>(test.scala:16)
[info]   at pickling.run.TraitWithAbstractValueTest$PicklingRunMessageUnpickler$macro$6$2$PicklingRunEventMessageUnpickler$macro$7$2$.unpickle(test.scala:45)
[info]   at pickling.run.TraitWithAbstractValueTest$PicklingRunMessageUnpickler$macro$6$2$.unpickle(test.scala:45)
[info]   at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[info]   at pickling.run.TraitWithAbstractValueTest$PicklingRunMessageUnpickler$macro$6$2$.unpickleEntry(test.scala:45)
[info]   at scala.pickling.functions$.unpickle(functions.scala:11)
[info]   at scala.pickling.UnpickleOps.unpickle(Ops.scala:23)
[info]   at pickling.run.TraitWithAbstractValueTest.fromPickle(test.scala:45)
[info]   at pickling.run.TraitWithAbstractValueTest$$anonfun$1.apply$mcV$sp(test.scala:52)
[info]   at pickling.run.TraitWithAbstractValueTest$$anonfun$1.apply(test.scala:48)
[info]   ...

```
