### ISSUE TITLE
Seq[Option[Seq[Double]]] Field Not Implemented

### ISSUE THREAD

**Issue by bwwinthehouse** [scala/pickling#260]
```scala
 scala> case class Test2(test:Seq[Option[Seq[Double]]])
defined class Test2

scala> Test2(Seq(Some(Seq[Double](1,2,3,4,5)))).pickle
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
	at scala.pickling.PicklerUnpicklerNotFound.pickle(Custom.scala:21)
	at scala.pickling.LowPriorityPicklersUnpicklers$$anon$1$$anonfun$pickle$1$$anonfun$apply$1.apply(Custom.scala:107)
	at scala.pickling.LowPriorityPicklersUnpicklers$$anon$1$$anonfun$pickle$1$$anonfun$apply$1.apply(Custom.scala:105)
	at scala.pickling.binary.BinaryPickleBuilder.putElement(BinaryPickleFormat.scala:143)
	at scala.pickling.LowPriorityPicklersUnpicklers$$anon$1$$anonfun$pickle$1.apply(Custom.scala:105)
	at scala.pickling.LowPriorityPicklersUnpicklers$$anon$1$$anonfun$pickle$1.apply(Custom.scala:104)
	at scala.collection.immutable.List.foreach(List.scala:318) 
```

**Comment by eed3si9n** [comment]
I could not reproduce the problem using Pickling 0.10.0.

``` scala
scala> import scala.pickling._, Defaults._, json._
import scala.pickling._
import Defaults._
import json._

scala> case class Test2(test:Seq[Option[Seq[Double]]])
defined class Test2

scala> Test2(Seq(Some(Seq[Double](1,2,3,4,5)))).pickle
res0: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "Test2",
  "test": {
    "$type": "scala.collection.Seq[scala.Option[scala.collection.Seq[scala.Double]]]",
    "elems": [
      {
      "$type": "scala.Some[scala.collection.Seq[scala.Double]]",
      "x": {
        "$type": "scala.collection.Seq[scala.Double]",
        "elems": [
          1.0,
          2.0,
          3.0,
          4.0,
          5.0
        ]
      }
    }
    ]
  }
})
```
