### ISSUE TITLE
cannot pickle Map

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/pickling#322]
scala 2.11.6 and 
"org.scala-lang.modules" %% "scala-pickling" % "0.10.0"

`Map(1 -> 1).pickle.value`

```
java.lang.NoClassDefFoundError: scala/pickling/FastTypeTag
  at com.scalakata.metadoc.plugin.MetadocPlugin.<init>(MetadocPlugin.scala:9)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
  at scala.tools.nsc.plugins.Plugin$.instantiate(Plugin.scala:190)
  at scala.tools.nsc.plugins.Plugins$$anonfun$loadRoughPluginsList$2.apply(Plugins.scala:47)
  at scala.tools.nsc.plugins.Plugins$$anonfun$loadRoughPluginsList$2.apply(Plugins.scala:47)
  at scala.collection.immutable.List.map(List.scala:273)
  at scala.tools.nsc.plugins.Plugins$class.loadRoughPluginsList(Plugins.scala:47)
  at scala.tools.nsc.Global.loadRoughPluginsList(Global.scala:40)
  at scala.tools.nsc.plugins.Plugins$class.roughPluginsList(Plugins.scala:50)
  at scala.tools.nsc.Global.roughPluginsList$lzycompute(Global.scala:40)
  at scala.tools.nsc.Global.roughPluginsList(Global.scala:40)
  at scala.tools.nsc.plugins.Plugins$class.loadPlugins(Plugins.scala:86)
  at scala.tools.nsc.Global.loadPlugins(Global.scala:40)
  at scala.tools.nsc.plugins.Plugins$class.plugins(Plugins.scala:102)
  at scala.tools.nsc.Global.plugins$lzycompute(Global.scala:40)
  at scala.tools.nsc.Global.plugins(Global.scala:40)
  at scala.tools.nsc.plugins.Plugins$class.computePluginPhases(Plugins.scala:113)
  at scala.tools.nsc.Global.computePluginPhases(Global.scala:40)
  at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:751)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at xsbt.CachedCompiler0$Compiler.superCall(CompilerInterface.scala:220)
  at xsbt.CachedCompiler0$Compiler.superComputePhaseDescriptors(CompilerInterface.scala:213)
  at xsbt.CachedCompiler0$Compiler.phaseDescriptors$lzycompute(CompilerInterface.scala:210)
  at xsbt.CachedCompiler0$Compiler.phaseDescriptors(CompilerInterface.scala:205)
  at scala.tools.nsc.Global$Run.<init>(Global.scala:1238)
  at xsbt.CachedCompiler0$$anon$2.<init>(CompilerInterface.scala:106)
  at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
  at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
  at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
  at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
  at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
  at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
  at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
  at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
  at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
  at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
  at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
  at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
  at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
  at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
  at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
  at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
  at sbt.inc.Incremental$.compile(Incremental.scala:61)
  at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
  at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
  at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
  at sbt.Compiler$.compile(Compiler.scala:128)
  at sbt.Compiler$.compile(Compiler.scala:114)
  at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:806)
  at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:797)
  at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:795)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
  at sbt.std.Transform$$anon$4.work(System.scala:63)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
  at sbt.Execute.work(Execute.scala:235)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.pickling.FastTypeTag
  at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
  at com.scalakata.metadoc.plugin.MetadocPlugin.<init>(MetadocPlugin.scala:9)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
  at scala.tools.nsc.plugins.Plugin$.instantiate(Plugin.scala:190)
  at scala.tools.nsc.plugins.Plugins$$anonfun$loadRoughPluginsList$2.apply(Plugins.scala:47)
  at scala.tools.nsc.plugins.Plugins$$anonfun$loadRoughPluginsList$2.apply(Plugins.scala:47)
  at scala.collection.immutable.List.map(List.scala:273)
  at scala.tools.nsc.plugins.Plugins$class.loadRoughPluginsList(Plugins.scala:47)
  at scala.tools.nsc.Global.loadRoughPluginsList(Global.scala:40)
  at scala.tools.nsc.plugins.Plugins$class.roughPluginsList(Plugins.scala:50)
  at scala.tools.nsc.Global.roughPluginsList$lzycompute(Global.scala:40)
  at scala.tools.nsc.Global.roughPluginsList(Global.scala:40)
  at scala.tools.nsc.plugins.Plugins$class.loadPlugins(Plugins.scala:86)
  at scala.tools.nsc.Global.loadPlugins(Global.scala:40)
  at scala.tools.nsc.plugins.Plugins$class.plugins(Plugins.scala:102)
  at scala.tools.nsc.Global.plugins$lzycompute(Global.scala:40)
  at scala.tools.nsc.Global.plugins(Global.scala:40)
  at scala.tools.nsc.plugins.Plugins$class.computePluginPhases(Plugins.scala:113)
  at scala.tools.nsc.Global.computePluginPhases(Global.scala:40)
  at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:751)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at xsbt.CachedCompiler0$Compiler.superCall(CompilerInterface.scala:220)
  at xsbt.CachedCompiler0$Compiler.superComputePhaseDescriptors(CompilerInterface.scala:213)
  at xsbt.CachedCompiler0$Compiler.phaseDescriptors$lzycompute(CompilerInterface.scala:210)
  at xsbt.CachedCompiler0$Compiler.phaseDescriptors(CompilerInterface.scala:205)
  at scala.tools.nsc.Global$Run.<init>(Global.scala:1238)
  at xsbt.CachedCompiler0$$anon$2.<init>(CompilerInterface.scala:106)
  at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
  at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
  at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
  at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
  at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
  at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
  at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
  at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
  at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
  at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
  at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
  at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
  at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
  at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
  at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
  at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
  at sbt.inc.Incremental$.compile(Incremental.scala:61)
  at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
  at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
  at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
  at sbt.Compiler$.compile(Compiler.scala:128)
  at sbt.Compiler$.compile(Compiler.scala:114)
  at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:806)
  at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:797)
  at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:795)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
  at sbt.std.Transform$$anon$4.work(System.scala:63)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
  at sbt.Execute.work(Execute.scala:235)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
[error] (testBench/compile:compileIncremental) java.lang.reflect.InvocationTargetException
[error] Total time: 8 s, completed Apr 15, 2015 4:48:05 PM
```

**Comment by MasseGuillaume** [comment]
nvm, it's just missing scala pickling in the packaged jar

**Comment by MasseGuillaume** [comment]
https://github.com/sbt/sbt-assembly/issues/151

**Comment by eed3si9n** [comment]
If sbt-assembly is messing up the JAR, that's not pickling's problem. I'm closing this issue.
