### ISSUE TITLE
Should this Set pickle-unpickle with val fail?

### ISSUE THREAD

**Issue by cos** [scala/pickling#324]
``` scala
scala> import scala.pickling.Defaults._, scala.pickling.json._
import scala.pickling.Defaults._
import scala.pickling.json._

scala> case class Foo(bar: Set[Int]) { val barSize = bar.size }
defined class Foo

scala> Foo(Set()).pickle
res27: pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "Foo",
  "bar": {
    "$type": "scala.collection.immutable.Set[scala.Int]",
    "elems": [

    ]
  }
})

scala> res27.unpickle[Foo]
java.lang.NullPointerException
  ... 49 elided

scala> lastException.printStackTrace
java.lang.NullPointerException
    at $line57.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$Foo.<init>(<console>:22)
    at $line59.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$line57$read$iw$iw$iw$iw$iw$iw$iw$iw$iw$iw$iw$iwFooUnpickler$macro$49$2$.unpickle(<console>:26)
    at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
    at $line59.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$line57$read$iw$iw$iw$iw$iw$iw$iw$iw$iw$iw$iw$iwFooUnpickler$macro$49$2$.unpickleEntry(<console>:26)
    at scala.pickling.functions$.unpickle(functions.scala:11)
    at scala.pickling.UnpickleOps.unpickle(Ops.scala:23)
    at $line59.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<init>(<console>:26)
    at $line59.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<clinit>(<console>)
    at $line59.$eval$.$print$lzycompute(<console>:7)
    at $line59.$eval$.$print(<console>:6)
    at $line59.$eval.$print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:773)
    at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
    at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:627)
    at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:626)
    at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
    at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:626)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:558)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:554)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:804)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:849)
    at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:707)
    at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:405)
    at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:431)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:920)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:906)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:906)
    at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:906)
    at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:931)
    at xsbt.ConsoleInterface.run(ConsoleInterface.scala:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
    at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:77)
    at sbt.Console.sbt$Console$$console0$1(Console.scala:23)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:24)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:24)
    at sbt.Logger$$anon$4.apply(Logger.scala:90)
    at sbt.TrapExit$App.run(TrapExit.scala:244)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by cos** [comment]
Hi, sorry to bug you about this. It would be helpful if someone could at least have a look and let us know if this is a bug or we are trying to use pickling in the wrong way. The issue is a bit of a roadblock for us now. Thanks!

**Comment by phaller** [comment]
Hi @cos, I'm having a look, and will post my findings when I know more.

**Comment by phaller** [comment]
@cos: this is a bug, and I've tracked it down; no usage issue on your side. Trying to find a good bug fix.

**Comment by cos** [comment]
Thank you, Philipp!
