### ISSUE TITLE
pickling code crashes jdk 1.8.0_45 on my mac osx

### ISSUE THREAD

**Issue by simbo1905** [scala/pickling#325]
The gist at https://gist.github.com/simbo1905/facb9cef0e8ceabb3715 shows a cut down version of code which causes the jvm to crash on my mac with: 

```
 A fatal error has been detected by the Java Runtime Environment:

  SIGBUS (0xa) at pc=0x00007fff925dc331, pid=19228, tid=4867

 JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode bsd-amd64 compressed oops)
 Problematic frame:
 C  [libsystem_platform.dylib+0x1331]  _platform_memmove$VARIANT$Ivybridge+0x31

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c nlimited" before starting Java again

 An error report file with more information is saved as:
 /Users/simbo/projects/trex/trex/hs_err_pid19228.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

Process finished with exit code 134
```

**Comment by nessus42** [comment]
I'm seeing this same error. (Also on a Mac, with Java build 1.8.0_25-b17 and Scala version 2.11.7.)

I only see the error, however, if the data has become corrupted in between picking and unpickling. I suppose we can live with this, but it might be nice if we received a sensible error message, rather than just having the JVM crash.

|>oug

P.S. I'm using version 0.10.2-SNAPSHOT.

P.P.S. Sometimes I get an OutOfMemoryError exception instead of the JVM crash. But what I'm trying to unpickle is not large and I have the heap size set to 8G. Here's an example stack trace:

```
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.StringCoding.safeTrim(StringCoding.java:89)
    at java.lang.StringCoding.access$100(StringCoding.java:50)
    at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:154)
    at java.lang.StringCoding.decode(StringCoding.java:193)
    at java.lang.String.<init>(String.java:414)
    at java.lang.String.<init>(String.java:479)
    at scala.pickling.binary.BinaryInput.getString(BinaryInput.scala:33)
    at scala.pickling.binary.BinaryInput.getStringWithLookahead(BinaryInput.scala:92)
    at scala.pickling.binary.BinaryPickleReader$$anonfun$1.apply(BinaryPickle.scala:187)
    at scala.pickling.binary.BinaryPickleReader$$anonfun$1.apply(BinaryPickle.scala:163)
    at scala.pickling.PickleTools$class.withHints(Tools.scala:521)
    at scala.pickling.binary.BinaryPickleReader.withHints(BinaryPickle.scala:159)
    at scala.pickling.binary.BinaryPickleReader.beginEntry(BinaryPickle.scala:163)
    at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
    at org.broadinstitute.gpp.runcible.http.FishrHttpClient$$anonfun$query$1$OrgBroadinstituteGppRuncibleApiFishrMatchesUnpickler$macro$1$2$.unpickleEntry(FishrHttpClient.scala:66)
    at scala.pickling.functions$.unpickle(functions.scala:6)
    at scala.pickling.UnpickleOps.unpickle(Ops.scala:23)
    at org.broadinstitute.gpp.runcible.http.FishrHttpClient$$anonfun$query$1.apply(FishrHttpClient.scala:66)
    at org.broadinstitute.gpp.runcible.http.FishrHttpClient$$anonfun$query$1.apply(FishrHttpClient.scala:59)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
