### ISSUE TITLE
List as type parameter error

### ISSUE THREAD

**Issue by milanraulim** [scala/pickling#35]
Hello,

I have this function:

```scala
def p [ A : SPickler : FastTypeTag ](a: A) = a.pickle
```

when I try to call it with `Seq[Int]  => p(Seq(1,2,3))` it returns 

```scala
scala.pickling.json.JSONPickle = 
JSONPickle({
  "tpe": "scala.collection.Seq[scala.Int]",
  "elems": [
    1,
    2,
    3
  ]
})
```

but if I try to call it with `List[Int] => p(List(1,2,3))` it causes exception

```
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
	at scala.pickling.PicklerUnpicklerNotFound.pickle(Custom.scala:19)
	at .p(<console>:17)
	at .<init>(<console>:19)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:745)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:790)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:702)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:566)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:573)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:576)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:867)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:889)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:73)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:64)
	at sbt.Console.console0$1(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
	at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
	at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
```

Thanks for your help,
Milan

**Comment by eed3si9n** [comment]
List works ok using Pickling 0.10.0.

``` scala
scala> import scala.pickling._, Defaults._, json._
import scala.pickling._
import Defaults._
import json._

scala> def p [A : Pickler : FastTypeTag](a: A) = a.pickle
p: [A](a: A)(implicit evidence$1: scala.pickling.Pickler[A], implicit evidence$2: scala.pickling.FastTypeTag[A])scala.pickling.json.pickleFormat.PickleType

scala> p(Seq(1, 2, 3))
res0: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "scala.collection.Seq[scala.Int]",
  "elems": [
    1,
    2,
    3
  ]
})

scala> p(List(1, 2, 3))
warning: there was one deprecation warning; re-run with -deprecation for details
res1: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "scala.collection.immutable.$colon$colon[scala.Int]",
  "head": 1,
  "tl": {
    "$type": "scala.collection.immutable.$colon$colon[scala.Int]",
    "head": 2,
    "tl": {
      "$type": "scala.collection.immutable.$colon$colon[scala.Int]",
      "head": 3,
      "tl": {
        "$type": "scala.collection.immutable.Nil.type"
      }
    }
  }
})
```
