### ISSUE TITLE
java.lang.NegativeArraySizeException when size is well over 0 

### ISSUE THREAD

**Issue by raam86** [scala/pickling#361]
code:

```
def unpickleEvent(e:Array[Byte]):Event = {
    println("unpickling event from array with size:",e.length)
    if(e.length > 0) e.unpickle[Event]
    else throw new RuntimeException("array size with less then 0")
  }
```

output:
(unpickling event from array with size:,24544)
15/08/10 14:17:48 ERROR Executor: Exception in task 0.0 in stage 3.0 (TID 3)
java.lang.NegativeArraySizeException
    at scala.reflect.ManifestFactory$$anon$6.newArray(Manifest.scala:93)
    at scala.reflect.ManifestFactory$$anon$6.newArray(Manifest.scala:91)
    at scala.Array$.ofDim(Array.scala:218)
    at scala.pickling.binary.BinaryInput.getByteArray(BinaryInput.scala:56)
    at scala.pickling.binary.BinaryInput.getString(BinaryInput.scala:32)
    at scala.pickling.binary.BinaryInput.getStringWithLookahead(BinaryInput.scala:92)
    at scala.pickling.binary.BinaryPickleReader$$anonfun$1.apply(BinaryPickle.scala:188)
    at scala.pickling.binary.BinaryPickleReader$$anonfun$1.apply(BinaryPickle.scala:164)
    at scala.pickling.PickleTools$class.withHints(Tools.scala:521)
    at scala.pickling.binary.BinaryPickleReader.withHints(BinaryPickle.scala:160)
    at scala.pickling.binary.BinaryPickleReader.beginEntry(BinaryPickle.scala:164)
    at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:78)
    at com.apester.etl.serializers.pickel$ComApesterEtlModelsEventUnpickler$macro$86$2$.unpickleEntry(pickel.scala:26)
    at scala.pickling.functions$.unpickle(functions.scala:11)
    at scala.pickling.UnpickleOps.unpickle(Ops.scala:23)
    at com.apester.etl.serializers.pickel$.unpickleEvent(pickel.scala:26)
    at com.apester.spark.toyStreaming$$anonfun$2.apply(toyStreaming.scala:74)
    at com.apester.spark.toyStreaming$$anonfun$2.apply(toyStreaming.scala:72)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:414)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:369)
    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:350)
    at scala.collection.Iterator$class.foreach(Iterator.scala:750)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:295)
    at scala.collection.AbstractIterator.to(Iterator.scala:1202)
    at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:287)
    at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1202)
    at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:274)
    at scala.collection.AbstractIterator.toArray(Iterator.scala:1202)
    at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$28.apply(RDD.scala:1276)
    at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$28.apply(RDD.scala:1276)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
    at org.apache.spark.scheduler.Task.run(Task.scala:70)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by raam86** [comment]
Sorry. I misunderstood
