### ISSUE TITLE
Can not pickle/unpickle a Map[String,Any]

### ISSUE THREAD

**Issue by piotrga** [scala/pickling#99]
I am using version 0.8.0-SNAPSHOT.

```scala
import org.scalatest.FreeSpec
import scala.pickling._
import scala.pickling.json._

class DynamicMapScalaPicklingTest extends FreeSpec{
  "Can pickle/unpickle a Map[String,Any]" in {
    val m = Map("a" -> 10, "b" -> "bbbb")
    val pickled = m.pickle
    println(s"$m pickled => $pickled")

    pickled.unpickle[Map[String, Any]] === m
  }
}
```
And I am getting this when unpickling:
```
cannot set an immutable field _2 
scala.ScalaReflectionException: cannot set an immutable field _2 
	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$ErrorSetImmutableField(JavaMirrors.scala:137)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaFieldMirror.set(JavaMirrors.scala:286)
	at plinkplink.DynamicMapScalaPicklingTest$$anonfun$1$ScalaTuple2$u005BjavaLangString$u002CjavaLangObject$u005DUnpickler2$2$.unpickle(DynamicMapScalaPicklingTest.scala:14)
	at scala.pickling.LowPriorityPicklersUnpicklers$$anon$1.unpickle(Custom.scala:133)
	at plinkplink.DynamicMapScalaPicklingTest$$anonfun$1.apply$mcV$sp(DynamicMapScalaPicklingTest.scala:14)
	at plinkplink.DynamicMapScalaPicklingTest$$anonfun$1.apply(DynamicMapScalaPicklingTest.scala:9)
	at plinkplink.DynamicMapScalaPicklingTest$$anonfun$1.apply(DynamicMapScalaPicklingTest.scala:9)
```

**Comment by eed3si9n** [comment]
This seems to work for Pickling 0.10.0.

``` scala
scala> import scala.pickling._, Defaults._, json._
import scala.pickling._
import Defaults._
import json._

scala> val m = Map("a" -> 10, "b" -> "bbbb")
m: scala.collection.immutable.Map[String,Any] = Map(a -> 10, b -> bbbb)

scala> val pickled = m.pickle
pickled: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "scala.collection.immutable.Map[java.lang.String,scala.Any]",
  "elems": [
    {
    "$type": "scala.Tuple2[java.lang.String,scala.Any]",
    "_1": "a",
    "_2": {
      "$type": "scala.Int",
      "value": 10
    }
  },
    {
    "$type": "scala.Tuple2[java.lang.String,scala.Any]",
    "_1": "b",
    "_2": {
      "$type": "java.lang.String",
      "value": "bbbb"
    }
  }
  ]
})

scala> pickled.unpickle[Map[String, Any]]
res0: Map[String,Any] = Map(a -> 10, b -> bbbb)

scala> res0 == m
res1: Boolean = true
```
